### ISSUE TITLE
There is no timeout scheduled with the given id "386"

### ISSUE THREAD

**Issue by LavanyaBurlagadda** [chrisguttandin/worker-timers-broker#281]
We are getting this issue when we are clearing the timeouts in the component unmounting stage.

Let's say that even if the timeout is executed if we try to clear the timeout it shouldn't throw an error.

We are getting sentry issues reported for this issue.
![Screenshot from 2023-08-01 11-33-00](https://github.com/chrisguttandin/worker-timers-broker/assets/48449639/e6768d12-3189-4bd9-a9f1-e9578c674e24)

**Comment by chrisguttandin** [comment]
I'm closing this in favor of chrisguttandin/worker-timers#433.
