### ISSUE TITLE
Patch release 6.1.2 killed Node.js 16 support

### ISSUE THREAD

**Issue by Apollon77** [chrisguttandin/worker-timers-broker#282]
Hi,

your version bump in https://github.com/chrisguttandin/worker-timers-broker/commit/61267bd2bcbf1a3f7513c71b77c9da2a55bedd90 lead to the effect that Node.js 16 is not no longer supported for your package and all that use this package, e.g. mqtt ... they are now broken and their engines entry https://github.com/mqttjs/MQTT.js/blob/main/package.json#L102 is kind of invalid.

```
npm ERR! engine Not compatible with your version of node/npm: fast-unique-numbers@9.0.0

npm ERR! notsup Not compatible with your version of node/npm: fast-unique-numbers@9.0.0

npm ERR! notsup Required: {"node":">=18.2.0"}

npm ERR! notsup Actual:   {"npm":"8.19.4","node":"v16.20.2"}
```

Can you please release a fixed patch version of the package (and same for worker-timers) and do the increase in a major version? ALternatively you should inform all upstream packages about this that they can adjust theor node.js version requirements. 

Thank you

**Comment by chrisguttandin** [comment]
Hi @Apollon77, I'm not sure how to solve this problem in a clean way.

`fast-unique-numbers` can be used in the browser or with Node.js. Therefore I released a major version when I removed tests for Node.js v16. But this package only uses `fast-unique-numbers` in the browser. Hence it is not effected by that change. That why I just updated the dependency on `fast-unique-numbers` without releasing a breaking change for this package.

On the other hand package managers don't seem to distinguish between packages that are installed to run on Node.js and those that contain code which gets bundled for the frontend and never runs on Node.js itself.

**Comment by Apollon77** [comment]
In fact fast-unique-numbers defines https://github.com/chrisguttandin/fast-unique-numbers/blob/main/package.json#L60-L62 a nodejs minimum version, so in fact you say there that this node.js version is required at minimum. If the version should still work with node.js 16 but you just don't test that anymore then you could simplyallow a wider node.js range there.

But if you limit this way then this bubbles up for all packages ...


So in my eyes:
* release a new version on fast-unique-numbers and change the minimum node.js version if it still work in that one, then this fixes it for all upstream packages
* if the limitation to >= 18.2.0 is real then in fact you should release major versions of the packages using it with the same nodejs limitation (and maybe another patch one to downgrade the dep for the "upstream packages that rely on the current versions

But yes the problem is that there is no way to tell where a depenedency is actually used ... thats meehh :-( I also have no easy solution, sorry.

**Comment by Apollon77** [comment]
@chrisguttandin Thank you very much!
